### ISSUE TITLE
Adding IPFS support to Homebrew

### ISSUE THREAD

**Issue by andrew** [ipfs/package-managers#12]
As mentioned in https://docs.google.com/document/d/1-HtUiRpMzYq9to56ShCGyCr-NCZ6TR49Zl-b5HHJdm0/edit#heading=h.m17gf4vdw67, adding IPFS support to "portable registry" package managers is fairly easy due to the fact that you can fork the whole registry and add hashes to the metadata.

As an experiment, I thought I'd give it a try with Homebrew.

I picked a simple ["Formula"](https://github.com/Homebrew/homebrew-core/blob/master/Formula/sl.rb) and added the tarball to ipfs:

    $ ipfs urlstore add https://github.com/mtoyoda/sl/archive/5.02.tar.gz
    
Which gives you the hash: `zb2rhYgkf18LAi1FjyZPZfU43UrxwBZgV59XrpKR3mCXfNAyX`

I then added that hash to the formula in my fork of homebrew-core: https://github.com/andrew/homebrew-core/commit/50b776ce8f2841457610a232a815267910a45f5c

![screenshot 2019-02-27 at 14 00 45](https://user-images.githubusercontent.com/1060/53495565-18619880-3a98-11e9-9556-0764f67b8070.png)

This extra field won't just work with the brew command, so I forked and patched homebrew to add support for the `ipfs` method: https://github.com/andrew/brew/commit/17492b84b5da49181eb9a6c601747adc5ebafc96 

This quick hack makes a few of assumptions: 

- you have the `ipfs` command installed in `/usr/local/bin/ipfs`, which is the default on mac when installed using homebrew
- you have `ipfs daemon` running, it doesn't try to start it for you
- you want to build from source, it doesn't work with prebuilt binaries, which homebrew calls `bottles`

Luckily with homebrew, you can install and run it from any directory, so it's easy to download my fork:

    $ git clone https://github.com/andrew/brew && cd brew

Then install my forked `sl` formula via IPFS:

    $ ./bin/brew reinstall andrew/core/sl --build-from-source

![screenshot 2019-02-27 at 12 37 46](https://user-images.githubusercontent.com/1060/53496115-3e3b6d00-3a99-11e9-91d6-60101d161192.png)

Also of note, homebrew checks the file that was downloaded from IPFS against the exist sha256 integrity hash and it matches 🎉 

Then you can run it:

    $ ./bin/sl 

![screenshot 2019-02-27 at 14 10 55](https://user-images.githubusercontent.com/1060/53496239-8490cc00-3a99-11e9-88e8-c43bb5b05856.png)

IPFS hashes could easily be added to most of the other ~4,700 formula homebrew core using a script to find the url of each formulas tarball, add it to ipfs, update the formula with the hash and commit, and then have a script to watch the homebrew repo for new formula updates.

I also briefly mentioned it to @mikemcquaid over SMS, overall he thought it was very neat, adding:

> FYI to avoid disappointment: we’re unlikely to add a new download strategy to Homebrew/brew until it’s required by a core formula as the main download method.

Some other homebrew notes:

Homebrew is very heavily used in the mac community for installing databases, languages and other system level packages, they also have public install analytics: https://formulae.brew.sh/analytics/install/30d/

![screenshot 2019-02-27 at 14 20 28](https://user-images.githubusercontent.com/1060/53496872-d8e87b80-3a9a-11e9-9c0c-c35f3cc27189.png)

They're also moving towards offering more precompiled binaries (bottles), currently hosted on https://bintray.com/homebrew 

Homebrew is also preinstalled on all Travis CI and Circle CI MacOS projects

**Comment by meiqimichelle** [comment]
@andrew what's the status of this experiment? (<-- ...you may be sensing a theme in my latest round of comments <3 )

**Comment by andrew** [comment]
This experiment is pretty much done for now, by the time we get back to it much of the actual code will need to be redone.
