### ISSUE TITLE
Categorizing by implementation

### ISSUE THREAD

**Issue by andrew** [ipfs/package-managers#14]
A slightly different approach to categorizing package managers than outlined in the [Glossary](https://github.com/protocol/package-managers/blob/master/glossary.md#categorizations) that I've been thinking about with regards to IPFS implementations specifically.

## File-system based

This maps closely to the [Multi-Registry](https://github.com/protocol/package-managers/blob/master/glossary.md#multi-registry) category.

Many system package managers ([APT](https://github.com/protocol/package-managers/blob/master/package-managers/dpkg.md), [apk](https://github.com/protocol/package-managers/blob/master/package-managers/apk.md), [RPM](https://github.com/protocol/package-managers/blob/master/package-managers/rpm.md) [pacman](https://github.com/protocol/package-managers/blob/master/package-managers/pacman.md), [portage](https://github.com/protocol/package-managers/blob/master/package-managers/portage.md)), plus some of the older language package managers ([Maven](https://github.com/protocol/package-managers/blob/master/package-managers/maven.md), [CPAN](https://github.com/protocol/package-managers/blob/master/package-managers/cpan.md), CRAN) are literally a network attached folder full of files and other folders, often exposed over http, ftp etc.

Metadata is also stored as files so everything is quite self-contained and easily mirrored using rsync. 

This style of registry maps nicely onto [IPFS MFS](https://docs.ipfs.io/guides/concepts/mfs/) and unixfs, it also seems like most sourcecode and binaries are stored within tar/zip/ar files to preserve any file permissions when downloaded over http, which conveniently means we don't need to wait for unixfs-v2 before implementing things.

Essentially, from IPFS point of view, all of these package managers end up having a very similar API (unixfs) that needs to be implemented, then the clients decide how they want to organise the files and metadata within that top level folder. A number of existing attempts take this approach ([arch-mirror](https://github.com/victorb/arch-mirror), [apt-transport-ipfs](https://github.com/JaquerEspeis/apt-transport-ipfs), [Gentoo-distfiles-IPFS](https://github.com/NiKiZe/Gentoo-distfiles-IPFS))

## Database based

This maps closely to the [Centralized Registry](https://github.com/protocol/package-managers/blob/master/glossary.md#centralized-registry) category.

Many newer language package managers ([rubygems](https://github.com/protocol/package-managers/blob/master/package-managers/rubygems.md), [npm](https://github.com/protocol/package-managers/blob/master/package-managers/npm.md), [Packagist](https://github.com/protocol/package-managers/blob/master/package-managers/composer.md), [PyPI](https://github.com/protocol/package-managers/blob/master/package-managers/pypi.md), [NuGet](https://github.com/protocol/package-managers/blob/master/package-managers/nuget.md), [Cargo](https://github.com/protocol/package-managers/blob/master/package-managers/cargo.md), [bower](https://github.com/protocol/package-managers/blob/master/package-managers/bower.md))  run a database-backed web application that handles authentication, uploading, provides APIs for the clients to list packages and versions and other metadata on demand.

Actual package contents is often hosted on s3 and requests to download packages may be proxied through the application to track download statistics, or redirected to a CDN link.

Mirroring these package managers usually requires either trawling package list APIs and recursively downloading packages and their metadata, or, if the registry provides it, downloading a dump of the registries database and running a copy of the web application or a slimmed down alternative that provides a similar API.

Unlike the file-system based package managers, almost every database based registry implements it's own, unique API for querying metadata and publishing packages.

This may explain why there are generally less public mirrors available for Centralized/database-backed package managers as there's a lot more overhead and complexity in keeping a mirror up to date than in the file-system based registries.

The one shared attribute they all share is that clients communicate with registries remotely via https urls, which can be proxied locally and backed by IPFS. A few existing implementations take this approach ([npm-on-ipfs](https://github.com/ipfs-shipyard/npm-on-ipfs), [dpip](https://github.com/AuHau/dpip/issues/1)), as well as general purpose artifact stores like [Sonatype Nexus](https://www.sonatype.com/nexus-repository-sonatype) and [Artifactory](https://jfrog.com/artifactory/).

## Git based

This maps to the [Portable Registry](https://github.com/protocol/package-managers/blob/master/glossary.md#portable-registry) and the [Registry-less](https://github.com/protocol/package-managers/blob/master/glossary.md#registry-less) categories.

### Portable Registries

A number of Portable registries ([Homebrew](https://github.com/protocol/package-managers/blob/master/package-managers/homebrew.md), [CocoaPods](https://github.com/protocol/package-managers/blob/master/package-managers/cocoapods.md)) use Git (usually GitHub) as a database rather than a traditional centralized database, often as a way to avoid becoming a full time, on-call DBA for their community.

One notable exception is Cargo's main registry, https://crates.io, which has parts of both a portable registry in https://github.com/rust-lang/crates.io-index and central database in https://github.com/rust-lang/crates.io

With Homebrew, PRs can be opened directly on their [GitHub repository database](https://github.com/homebrew/homebrew-core/) to add and update Formula files, which contain the metadata for a package, including links to the source and compiled binaries with integrity hashes.

With CocoaPods, you used to be able to send PRs to their [GitHub repository database](https://github.com/CocoaPods/Specs) but after they merged a PR publishing a new version by someone who shouldn't have been able to, they [implemented](http://blog.cocoapods.org/CocoaPods-Trunk/) a separate web service called [Trunk](https://github.com/CocoaPods/trunk.cocoapods.org) to handle adding new version to the git database. 

Similarly with Crates.io, their [GitHub repository database](https://github.com/rust-lang/crates.io-index) is updated automatically whenever someone publishes a new version via the crates.io website.

In all three of these cases, the end user only ever uses data from the latest commit that they have locally, tags and branches are not utilized and in the case of Cocoapods and Cargo, the history of the repository is not used for previous versions, in fact end users often do a shallow clone (`git clone --depth 1` so don't even have history data to go back on. 

Homebrew only keeps the latest version of a Formula in it's database, but does clone the full repository (243.22 MiB as of February 2019) so users can check out previous revisions of the repository to install old versions of a Formula, although it's not encouraged (Formula cannot declare a particular version of a dependency) because the speed of operations on the large repo are slow.

When it comes to mapping these registries onto IPFS, git is used both as a transport protocol and storage mechanism, [git-remote-ipld](https://github.com/ipfs-shipyard/git-remote-ipld) should be able to help with integration.

There is a restriction that files stored in those repositories [can't be larger than 2MiB](https://github.com/ipfs-shipyard/git-remote-ipld/issues/6#issuecomment-362256240) but it doesn't look like any of those three databases store metadata files larger than a few Kb.

But none of the git repository databases actually contain the code of the releases, usually they have  URIs (homebrew can reference SVN, CVS, Git and other protocols, not just http), which are hosted elsewhere, often GitHub, but could be arbitrary. 

For IPFS to host both the registry and source code, each one of these remote URIs will need to be referenced either along side an IPFS CID (see https://github.com/protocol/package-managers/issues/12) or loaded via some kind of http proxy extension added to the client.

### Registry-less

Some package managers ([Go](https://github.com/protocol/package-managers/blob/master/package-managers/go.md), Carthage, Swiftpm) do away with hosted registries all together, instead preferring to declare dependencies as fully qualified http urls or shortcuts for GitHub urls (owner/repo-name for example).

These package managers often have support for checking to see if the url is a git repository and then querying for git tags as the list of published, named versions, and git commits as a full list of all possible versions (named by git commit sha and/or branch). 

The end result is instead of a single registry, these package managers have thousands of single project registries, and rely on APIs in Git and/or GitHub for metadata on releases.

When it comes to mapping these package managers onto IPFS, putting any individual repository on IPFS is relatively easy with [git-remote-ipld](https://github.com/ipfs-shipyard/git-remote-ipld), again with the restriction of 2MiB files, luckily none of the registry-less package managers support sharing binaries in the same way.

Rather the problem comes when declaring dependencies, which are often simple URIs within source code:

    import("github.com/golang/dep/internal/fs")

this can be swapped out with an IPFS CID, as seen with [gx](https://github.com/whyrusleeping/gx) :

    import(pstore "gx/ipfs/QmaCTz9RkrU13bm9kMB54f7atgqM4qkjDZpRwRoJiWXEqs/go-libp2p-peerstore")

But the original metadata of the package, such as upstream source and version number) is lost.

In addition, this import functionality is baked into the language implementation itself, making changes much more difficult than in external tooling.

**Comment by jessicaschilling** [comment]
@andrew What would you think about moving this, as an addendum to https://github.com/ipfs/package-managers/blob/master/glossary.md, into the docs directory?

**Comment by andrew** [comment]
👍

**Comment by andrew** [comment]
This now lives in the docs folder of the repo: https://github.com/ipfs/package-managers/blob/master/docs/categories.md

**Comment by momack2** [comment]
This comment (https://github.com/ipfs/package-managers/issues/14#issuecomment-471646464) is really valuable and didn't make it into the docs. Think we can find a way for these useful thoughts to live on?

**Comment by jessicaschilling** [comment]
@momack2 Do you mean what’s in the docs directory at https://github.com/ipfs/package-managers/blob/master/docs/categories.md or are you referring to a different piece of content?

**Comment by momack2** [comment]
I'm specifically referencing the https://github.com/ipfs/package-managers/issues/14#issuecomment-471646464 with the approaches and problems for each area. AFAIK that isn't covered in the docs you linked.

**Comment by jessicaschilling** [comment]
Separated this comment into a [new document](https://github.com/ipfs/package-managers/blob/master/docs/category-based-implementation.md) and referenced it in the [docs index](https://github.com/ipfs/package-managers/blob/master/docs/readme.md).  @andrew -- feel free to append/amend as you see fit.
