### ISSUE TITLE
Experiment: Setting up an Ubuntu mirror on IPFS

### ISSUE THREAD

**Issue by andrew** [ipfs/package-managers#18]
I thought it'd be interesting to try and replicate what was attempted in [this thread ](https://discuss.ipfs.io/t/ubuntu-archive-on-top-of-ipfs/1579)just over a year ago to see if similar performance problems exist when in adding a large file-system based package manager to IPFS.

Steps outlined below:

Spun up a ["Store-1-S" Online.net](https://www.online.net/en/dedicated-server#anchor-store) dedicated server in France with Ubuntu 18.04:

![screenshot 2019-03-08 at 13 16 22](https://user-images.githubusercontent.com/1060/54035517-75a0cc80-41b1-11e9-9c34-ea75c7fdba35.png)

Followed https://wiki.ubuntu.com/Mirrors/Scripts to rsync a mirror into `/data/apt`:

```
$ rsync --recursive --times --links --safe-links --hard-links --stats --exclude "Packages*" --exclude "Sources*" --exclude "Release*" --exclude "InRelease" rsync://archive.ubuntu.com/ubuntu /data/apt/
```

Output from rsync:

```
Number of files: 983,559 (reg: 910,696, dir: 58,765, link: 14,098)
Number of created files: 781,684 (reg: 721,325, dir: 47,528, link: 12,831)
Number of deleted files: 0
Number of regular files transferred: 722,538
Total file size: 1,297,227,684,984 bytes
Total transferred file size: 913,052,882,058 bytes
Literal data: 912,253,989,263 bytes
Matched data: 798,892,795 bytes
File list size: 41,354,902
File list generation time: 0.001 seconds
File list transfer time: 0.000 seconds
Total bytes sent: 16,633,996
Total bytes received: 912,544,392,481

sent 16,633,996 bytes  received 912,544,392,481 bytes  72,204,852.35 bytes/sec
total size is 1,297,227,684,984  speedup is 1.42
```

At this point `/data/apt` is about 1.2TB

Then installed ipfs:

```
$ wget https://dist.ipfs.io/go-ipfs/v0.4.19/go-ipfs_v0.4.19_linux-amd64.tar.gz
$ tar xvfz go-ipfs_v0.4.19_linux-amd64.tar.gz
$ cd go-ipfs
$ ./install.sh
```

Based on notes from https://github.com/ipfs/notes/issues/212, made the following config changes:

```
$ export IPFS_PATH=/data/.ipfs
$ export IPFS_FD_MAX=4096

$ ipfs init

$ ipfs config Reprovider.Interval "0"
$ ipfs config --json Datastore.NoSync true
$ ipfs config --json Experimental.ShardingEnabled true
$ ipfs config --json Experimental.FilestoreEnabled true

$ ipfs daemon
```

Then ran the following command to add `/data/apt` to IPFS:

```
$ ipfs add -r --progress --offline --fscache --quieter --raw-leaves --nocopy /data/apt
```

![screenshot 2019-03-08 at 09 40 59](https://user-images.githubusercontent.com/1060/54036243-fe6c3800-41b2-11e9-926f-fbc0c5257d18.png)

I then took the dog for a walk 🐩 🚶 

Output from `dstat` at various times over the next few hours:

![screenshot 2019-03-08 at 11 40 20](https://user-images.githubusercontent.com/1060/54036326-47bc8780-41b3-11e9-8e3a-fa2b502c7560.png)
(sorry about the colours here)

![screenshot 2019-03-08 at 12 27 18](https://user-images.githubusercontent.com/1060/54036336-4d19d200-41b3-11e9-8466-384ede9dab11.png)
It got "stuck" here around 30% (~345GB), progress bar didn't show any changes, slowly writing to disk.

`/data/.ipfs` dir was 441Mb for 345gb uploaded

Had some lunch 🍜 

![screenshot 2019-03-08 at 13 17 00](https://user-images.githubusercontent.com/1060/54036519-bac5fe00-41b3-11e9-9d2b-7d669eba1dac.png)
Came back to life whilst I was at lunch

`/data/.ipfs` dir was 862Mb for 532GB uploaded after about 3 hours.

Status as of 3pm:
- runtime: 5 hours
- percentage complete: 67%
- total filesize added to ipfs: 817GB
- size of `/data/.ipfs`: 1.3Gb
- dstat output:

![screenshot 2019-03-08 at 15 11 37](https://user-images.githubusercontent.com/1060/54036834-7e46d200-41b4-11e9-972e-99984ddc38d0.png)

<hr>

![screenshot 2019-03-08 at 15 17 56](https://user-images.githubusercontent.com/1060/54037184-72a7db00-41b5-11e9-9748-35cd385de953.png)

3:15pm progress slowed again, lots of writing, no reading

<hr>

4:15pm back to full speed again:
- runtime: 6 hours
- percentage complete: 74%
- total filesize added to ipfs: 904GB
- size of `/data/.ipfs`: 1.6Gb
- dstat output:

<img width="1760" alt="screenshot 2019-03-08 at 16 15 26" src="https://user-images.githubusercontent.com/1060/54040528-82c3b880-41bd-11e9-8a41-b2a8e692a39f.png">

<hr>

5:30pm progress slowed again, lots of writing, no reading, seems to be happening every hour

- runtime: 7 hours
- percentage complete: 85%
- total filesize added to ipfs: 1.01TB
- size of `/data/.ipfs`: 1.9Gb
- dstat output:

<img width="1760" alt="screenshot 2019-03-08 at 17 27 17" src="https://user-images.githubusercontent.com/1060/54044720-93792c00-41c7-11e9-8d04-8f6955006d09.png">

<hr>

6:20pm back to full speed again:
- runtime: 8 hours
- percentage complete: 90%
- total filesize added to ipfs: 1.07TB
- size of `/data/.ipfs`: 2.1Gb

<hr>

7:20pm stuck at 100% similar disk writing pattern, no CID returned yet:
- runtime: 9 hours
- percentage complete: 100%
- total filesize added to ipfs: 1.18TB
- size of `/data/.ipfs`: 2.3Gb

8:15pm: still stuck at 100%, similar disk writing pattern, no CID returned yet

<hr>
Will update this issue as it continues.

Drop a comment with any commands you'd like to see the output for during or after.

**Comment by andrew** [comment]
Moved apt-on-ipfs into the ipfs-shipyard org: https://github.com/ipfs-shipyard/apt-on-ipfs

Also added a mirror.sh script that is currently running every 4 hours via cron to keep the mirror up to date: https://github.com/ipfs-shipyard/apt-on-ipfs/blob/master/mirror.sh

**Comment by makeworld-the-better-one** [comment]
Does anyone have data on client bandwidth, for installing single package over IPFS versus the same package over apt?

**Comment by NatoBoram** [comment]
Strange, I'm also getting `internalWebError: operation not supported` on my own IPFS instance. I reported it in https://github.com/ipfs/go-ipfs/issues/6203.

As for the IPNS hash, I'm personally getting `ipfs resolve -r /ipns/QmTeHfjrEfVDUDRootgUF45eZoeVxKCy3mjNLA8q5fnc1B: context deadline exceeded`.

I also used [this tool](https://ipfs.io/ipfs/QmYSBFMAo7NFcapLoW4UTAnnPnwBGNB944HrENgrXbkg5k/) to check for the IPNS availability, but it seems like no one's able to get it.

**Comment by andrew** [comment]
@NatoBoram I've been off sick for a couple weeks and it looks like the ipfs daemon fell over on the mirror server at some point, I've restarted it now, that ipns name should start resolving again after the next successful cron job run within a few hours.

**Comment by andrew** [comment]
FYI I'm going to be turning off the machine that was running the experimental mirror on 2019-07-01

**Comment by meiqimichelle** [comment]
@andrew what's the status of this experiment? Could we (literal 'we', not royal 'we', lol) summarize, share, and archive, or is there more here to do?

**Comment by andrew** [comment]
"summarize, share, and archive" sounds like a good next step, this will form the basis for a lot of bench-marking and testing of file-system based package managers this quarter.

**Comment by makeworld-the-better-one** [comment]
@andrew I asked this above: 
> Does anyone have data on client bandwidth, for installing single package over IPFS versus the same package over apt?

It'd be good to see client data in general, to help us understand the pros and cons of using IPFS in this scenario for a client.

cc @Mikaela
