### ISSUE TITLE
📦 Unpacking the Package Managers Usecase 

### ISSUE THREAD

**Issue by daviddias** [ipfs/package-managers#2]
As promised during yesterday's [PL IPFS Team Call (Jan 29)](https://docs.google.com/document/d/1hnxY3GtRsaoNTQPegMNhjRRGMDq79uzmIeAGoCIpHIs/edit#heading=h.p1ahqhdtf25j) and [Project WG Weekly Sync (Jan 29)](https://docs.google.com/document/d/1IZ8tyWKnuXKTMbYaZO_8FVUKJ1kxA4imgPaTBhXXbAc/edit#heading=h.jv90fgbfwhk), I come here to present my first stab at unpacking (more untangling) what we know and don't know about Package Managers, creating a soundboard for continuous brainstorming.

This is of course a first pass with the time I had available today, there is lot more to do. I want to give you an update today as promised and I do believe it is best to share with you at this stage so that now we have shared resources to brainstorm around it.

The docs to look for are:

- [Package Manager Requests & Pre-boot Discussion](https://docs.google.com/document/d/1wdG5dDBCqnBk5sbqFjuJhLU5UkSJ5TcV2h39OlbnTcI/edit#heading=h.964qc2uu4xgk)
- [Requirements for Package Managers](https://docs.google.com/spreadsheets/d/1tObCjWE5bTcTCGUK0MMJ5R6OB64HPoDaibnGnHgCvAc/edit#gid=0)
- [(NEW) The Package Managers Usecase](https://docs.google.com/document/d/1z7bN9xdrtNJD_fvbi0pHA5p1O8-uUqvpu2U9lfAlXFc/edit#)

I'll avoid duplicating the information into this issue as you can read it directly in the doc. Nevertheless, here are brief introductions and a quick birds eye view of their contents

# [Package Manager Requests & Pre-boot Discussion](https://docs.google.com/document/d/1wdG5dDBCqnBk5sbqFjuJhLU5UkSJ5TcV2h39OlbnTcI/edit#heading=h.964qc2uu4xgk)

<img width="696" alt="image" src="https://user-images.githubusercontent.com/1211152/51990784-0fd26e00-24aa-11e9-9854-d4122aa57429.png">

This document is effectively a brain dump. I groomed it to have its information organized. You can learn here about what is the state of the multiple conversations with package managers people, what we learned so far and notes on what is next. It is also a great index to all previous discussions.

# [Requirements for Package Managers](https://docs.google.com/spreadsheets/d/1tObCjWE5bTcTCGUK0MMJ5R6OB64HPoDaibnGnHgCvAc/edit#gid=0)

<img width="1623" alt="image" src="https://user-images.githubusercontent.com/1211152/51990810-1a8d0300-24aa-11e9-8c8a-b2ade42522fb.png">

This spreadsheet is the result of a Deep Dive during the 2018 Dev Meetings in Berlin. It is a framework to capture info about each package manager ecosystem.

# [The Package Managers Usecase](https://docs.google.com/document/d/1z7bN9xdrtNJD_fvbi0pHA5p1O8-uUqvpu2U9lfAlXFc/edit#)

<img width="652" alt="image" src="https://user-images.githubusercontent.com/1211152/51990768-05b06f80-24aa-11e9-951e-1cb3128da55c.png">

This is a new document. It is the soundboard that is mention on the first paragraph. It packs and introduction to why Package Managers as a usecase and presents sections with prompts for us to collectively gather the known knowns and the known questions we have to answer.

Please read them and ask all your questions either here or through comments on the docs directly :) Have fun reading it all 📖 👓 🤯

**Comment by jessicaschilling** [comment]
@andrew Is this issue a candidate for your add-to-docs-directory effort?

**Comment by andrew** [comment]
@jessicaschilling yeh good call

**Comment by meiqimichelle** [comment]
I believe all of this has been transferred to other places in this repo (most likely all in the [docs directory](https://github.com/ipfs/package-managers/tree/master/docs) ). I'm going to close this issue as done since conversation about the package manager use case has well and truly been kicked off and moving forward 🎉 . 

@andrew or others -- please re-open if everything here hasn't been documented/linked elsewhere, and drop a status update.
