### ISSUE TITLE
Q2 2019 OKR - Design 2x elective sessions for IPFS Camp

### ISSUE THREAD

**Issue by achingbrain** [ipfs/package-managers#31]
In support of IPFS Camp produce 2x elective sessions related to package managers for the afternoons.

**Comment by achingbrain** [comment]
It's unclear what the content of these sessions would be.  From our conversations our audience is either package manager maintainers or users of package managers.

Maintainers would get the most value out of these sessions if we did something like how to import TBs of data, or how to make content available without doubling your storage requirements (for example) but there are only a handful of maintainers in the world and it would be hard to get 30 of them in the same room at the same time (e.g. the IPFS Camp class size).

Users of package managers would hopefully never notice they are using IPFS so it's hard to say what they would hope to take away from a session.

**Comment by andrew** [comment]
Suggestion by @daviddias:

> Possible not-quite-package-manager elective is "How to design, build and deploy large IPFS based web applications"

**Comment by jessicaschilling** [comment]
It may be outside the scope of IPFS Camp (i.e. it's not an educational session), but have we considered using the opportunity of a session to act as brainstorming for package manager _users_ to continue to elaborate on use cases/pain points/thoughts on the then-current state of IPFS/package manager integration?

**Comment by andrew** [comment]
@jessicaschilling that sounds like a great idea! 💯

**Comment by momack2** [comment]
+1 to a participatory package managers brainstorm! Sounds like a "Deep-dive" - I added that to the list of ideas: https://docs.google.com/document/d/1wFq7uX1MS-ZjnKRVNSMKzThE9LdIw2D3gKPai3CEKAI/edit#heading=h.cso2oviuqgtb

**Comment by jessicaschilling** [comment]
Cool. :) The session would benefit from having someone with more technical breadth in the room as well, but I'm happy to lead the overall direction of the session if I could enlist some help with the deep functional questions that will come up!
