### ISSUE TITLE
Invite package manager maintainers to IPFS Camp

### ISSUE THREAD

**Issue by Stebalien** [ipfs/package-managers#32]
Given our focus on package managers, we need to reach out to package manager maintainers and contributors and invite them to apply to IPFS Camp.

cc @momack2

**Comment by momack2** [comment]
Add invitee suggestions here: https://docs.google.com/spreadsheets/d/15URUMGNrFXF4z0Ft3IHoN-2TyBiIAMLRdMm4xao7o-c

**Comment by momack2** [comment]
I chatted with @daviddias about this today. We agree that trying to invite _all_ the maintainers of package managers to apply to IPFS Camp won't be a good fit - but we **SHOULD** have a track for those that are already on the decentralization wagon or are interested in making their own package manager on ipfs (prototype). We already have a guix application and I hope we get more!! 

In terms of content, we could have an elective course on how to set up an IPFS package mirror, show the various experiments we've tried so far, and then do some deep dives on the path forward to improve support and make IPFS more usable for package managers. Hopefully there will be some demo-building time in the evenings and during the electives - so IPFS Camp should be a valuable time to get folks up and running with something they can demo by EOWeekend. @andrew - do you think that qualifies as "Awesome - I can think of 5+ maintainers who'd love to come to that" or are there some tweaks to make it even better?

@olizilla re our conversation in the project wg yesterday - there will be lots of dapp folks at IPFS Camp, but they aren't the sum total of our audience/user base and therefore I don't think we should over-tune all the core and elective courses to just target existing champions. We want IPFS to be internet-scale, and that means reaching out to more use cases with internet-scale performance/scalability needs (and working hard to improve IPFS for those uses). IPFS Camp definitely won't be a "package manager specific" gathering - but we should use this opportunity to build connections and excitement with key members of this priority use case! =] 

((For a package-manager-specific gathering - maybe it's better if we go to them? @andrew @achingbrain - maybe a Q3 agenda item could be attending some different package manager  meetups to both share experiments and gather more feedback?))

**Comment by mikeal** [comment]
Fred Schott is one of the primary developers on Pika and they have
considering adding non-npm package management. He works at Ripple so he's
more familiar than the average developer with decentralization and IPFS.
http://fredkschott.com/about/

**Comment by andrew** [comment]
We should definitely include a mention of IPFS camp in the Package manager announcement blog post (aiming for next week as I've been off sick most of this week) 

For Q3, there aren't exactly that many package manager events that exist, we'll likely have to kickstart one to make that happen. I've been going on about getting package manager maintainers together in a room for a long time (the podcast was inspired by this line of thought).

**Comment by meiqimichelle** [comment]
Camp is now past. Closing.
