### ISSUE TITLE
Add the public call to the community calendar

### ISSUE THREAD

**Issue by alanshaw** [ipfs/package-managers#33]
Community calendar listing all the IPFS community calls is here: https://calendar.google.com/calendar/embed?src=ipfs.io_eal36ugu5e75s207gfjcu0ae84%40group.calendar.google.com&ctz=Europe%2FLondon

Please add so that other community members can also join.

refs https://github.com/ipfs/package-managers/issues/1

**Comment by achingbrain** [comment]
Hmm, I can't seem to write anything to that calendar

**Comment by andrew** [comment]
maybe @momack2 can help with that

**Comment by achingbrain** [comment]
I've emailed it@, maybe they can sort me out.

**Comment by momack2** [comment]
Gave it a shot - that work?

**Comment by momack2** [comment]
This seems to be fixed AFAICT.
