### ISSUE TITLE
Document stages/types of interplanetary package managers

### ISSUE THREAD

**Issue by momack2** [ipfs/package-managers#41]
In conversing with wasmer.io, I noticed a gap in our documentation - it'd be really nice to have a canonical place to point people around the different flavors/stages of interplanetary package managers. What are the different stages a package manager might explore or go through to fully "IPFS-ify" itself? What are the various benefits you get out of each type of integration? Which are best for different constraints?

I imagine something like:

**Backup export on IPFS:** intermittently dump the entire repository to IPFS and let the community pin
Benefits: Some community members may help replicate the contents as an additional backup mechanism in case the central repo ever is lost/corrupted

**Alternate transport:** maintain a regularly updated central mirror on IPFS as an alternative download transport
Benefits: etc

.
.
.
@jessicaschilling

**Comment by momack2** [comment]
@jessicaschilling

**Comment by andrew** [comment]
Related to [Example use cases relevant to package managers](https://github.com/ipfs/package-managers/issues/25) and [Primer for package manager maintainers that makes the case for IPFS simply & effectively](https://github.com/ipfs/package-managers/issues/26) OKRs

**Comment by andrew** [comment]
Started work on on a draft here: https://docs.google.com/document/d/12RiLaiTXHJh3jVRkGOCsb4C7Dd-mmU77Gi-cq4xCGFg/edit?usp=sharing

**Comment by meiqimichelle** [comment]
Ooooo, nice doc! Question regarding the "necessary parts list" at the top of the doc...

IPFS
- CIDs ✅
- Pinning 

IPLD ✅
- Unixfs
- Mfs 

Libp2p
- DHT

IPNS ✅
- DNSLink ✅

...I believe we have teams working on improving the usability of some, but not all, of those pieces. Is that something we need to address? ie, if package managers need these parts, do we have (or need) a few people specifically focused on each top-level bullet item (I think we have this covered for most on this list, but maybe not all)? Or, do we need to come up with explicit suggestions for (temporary!) work-arounds? Or develop some work-arounds ourselves for the time being to support adoption?

**Comment by andrew** [comment]
@meiqimichelle that top bit is a todo list of areas to cover in the rest of the document

**Comment by andrew** [comment]
Going to be moving the content of this issue into the `/docs` in the repository in https://github.com/ipfs/package-managers/pull/53
