### ISSUE TITLE
Interesting academic papers related to package management

### ISSUE THREAD

**Issue by andrew** [ipfs/package-managers#56]
I started a making a list of published papers that appeared relevant to package manager research and software dependencies, figured it'd be useful to share it. Feel free to add more in the comments.

- [A Look In the Mirror: Attacks on Package Managers](https://isis.poly.edu/~jcappos/papers/cappos_mirror_ccs_08.pdf)
- [Automatic Software Dependency Management using Blockchain](http://trap.ncirl.ie/3300/1/gavindmello.pdf)
- [Reflections on Trusting Trust](https://www.archive.ece.cmu.edu/~ganger/712.fall02/papers/p761-thompson.pdf)
- [SPAM: a Secure Package Manager](https://cseweb.ucsd.edu/~dstefan/pubs/brown:2017:spam.pdf)
- [Toward Decentralized Package Management](https://portail.telecom-bretagne.eu/publi/public/fic_download.jsp?id=5756)
- [Why do software packages conflict?](https://dl.acm.org/citation.cfm?id=2664470 ) 
- [Dependency solving](https://dl.acm.org/citation.cfm?id=2330431 )
- [A modular package manager architecture](https://dl.acm.org/citation.cfm?id=2401012 ) 
- [A method to generate traverse paths for eliciting missing requirements](https://dl.acm.org/citation.cfm?id=3290697)
- [MPM: a modular package manager](https://dl.acm.org/citation.cfm?id=2000255) 
- [A look in the mirror: attacks on package managers](https://dl.acm.org/citation.cfm?id=1455841)
- [Towards efficient optimization in package management systems](https://dl.acm.org/citation.cfm?id=2568306 ) 
- [On software component co-installability](https://dl.acm.org/citation.cfm?id=2025149 )
- [Package upgrades in FOSS distributions: details and challenges](https://dl.acm.org/citation.cfm?id=1490292) 
- [On the use of package managers by the C++ open-source community](https://dl.acm.org/citation.cfm?id=3167290) 
- [An adaptive package management system for scheme](https://dl.acm.org/citation.cfm?id=1297093) 
- [NixOS: a purely functional Linux distribution](https://dl.acm.org/citation.cfm?id=1411255 )
- [On the topology of package dependency networks: a comparison of three programming language ecosystems](https://dl.acm.org/citation.cfm?id=3003382)
- [When It Breaks, It Breaks: How Ecosystem Developers Reason about the Stability of Dependencies](https://dl.acm.org/citation.cfm?id=2916370)
- [On the Development and Distribution of R Packages: An Empirical Analysis of the R Ecosystem](https://dl.acm.org/citation.cfm?id=2797476)
- [Software engineering with reusable components](https://dl.acm.org/citation.cfm?id=260943) 
- [A look at the dynamics of the JavaScript package ecosystem](https://dl.acm.org/citation.cfm?id=2901743)
- [A historical analysis of Debian package incompatibilities](https://dl.acm.org/citation.cfm?id=2820545) 
- [Mining component repositories for installability issues](https://dl.acm.org/citation.cfm?id=2820524) 
- [The Evolution of Project Inter-dependencies in a Software Ecosystem: The Case of Apache](https://dl.acm.org/citation.cfm?id=2550583 )
- [OPIUM: Optimal Package Install/Uninstall Manager](https://dl.acm.org/citation.cfm?id=1248851)
- [How the Apache community upgrades dependencies: an evolutionary study](https://dl.acm.org/citation.cfm?id=2821962) 
- [The Spack Package Manager: Bringing Order to HPC Software Chaos](https://tgamblin.github.io/pubs/spack-sc15.pdf)
- [PubGrub: Next-Generation Version Solving](https://medium.com/@nex3/pubgrub-2fb6470504f)

**Comment by jessicaschilling** [comment]
@andrew could this live in an .md file in the docs directory too? As kind of a permanent reference reading list?

**Comment by andrew** [comment]
@jessicaschilling yeah, I've shared this issue in a few chat rooms and on twitter to see if there are any other significant ones I've missed, should definitely roll it into #53 though 👍

**Comment by jdorfman** [comment]
How Awesome™ Lists are born

**Comment by boegel** [comment]
A few more on [EasyBuild](http://easybuilders.github.io/easybuild):

* [EasyBuild: Building Software With Ease](https://easybuilders.github.io/easybuild/files/easybuild-PyHPC-SC12_paper.pdf)
* [Modern Scientific Software Management Using EasyBuild and Lmod](https://easybuilders.github.io/easybuild/files/hust14_paper.pdf)
* [Making Scientific Software Installation Reproducible On Cray Systems Using EasyBuild](https://cug.org/proceedings/cug2016_proceedings/includes/files/pap145s2-file1.pdf)

**Comment by andrew** [comment]
Going to be moving the content of this issue into the /docs in the repository in #53

**Comment by mschwager** [comment]
Also: [Small World with High Risks: A Study of Security Threats in the npm Ecosystem](https://arxiv.org/pdf/1902.09217.pdf)
