### ISSUE TITLE
Package Manager Q3 OKRs

### ISSUE THREAD

**Issue by andrew** [ipfs/package-managers#69]
We should decided on them and add them to the shared spreadsheet [here](https://docs.google.com/spreadsheets/d/1AiNUL7vK5Jp8aa839UaMaI_AlBU5r6Bor-A40179I2A/edit#gid=1685270127).

**Comment by andrew** [comment]
Current draft of ideas [here](https://docs.google.com/document/d/1KXWJYmTrJcUR50C83SHH3gmpL-nTkq-Fe6qTxRdm7r4/edit#heading=h.7a2ejvl8zen)

**Comment by meiqimichelle** [comment]
Draft ideas are now in the [IPFS 2019 Q3 public OKR spreadsheet](https://docs.google.com/spreadsheets/d/1AiNUL7vK5Jp8aa839UaMaI_AlBU5r6Bor-A40179I2A/edit#gid=1685270127) -- comment/edit/suggest on anything that doesn't look right, could be better, or needs to be added, plz!

**Comment by meiqimichelle** [comment]
It is now Q4. Closing.
