### ISSUE TITLE
Change repo naming and description from SIG to task force

### ISSUE THREAD

**Issue by andrew** [ipfs/package-managers#70]

**Comment by meiqimichelle** [comment]
@andrew @jessicaschilling does either of you have the original image file (editable) for the fancy repo title in the README?

**Comment by jessicaschilling** [comment]
Yep, I'll send it under separate cover.

**Comment by meiqimichelle** [comment]
Done! (Also added link to Zenhub task board)
![Screenshot 2019-07-15 09.32.04.png](https://images.zenhubusercontent.com/545cf2bf7c6ccc6277a5e45a/90b24ab1-13ba-441c-9b19-033b5edc3b4d)
