### ISSUE TITLE
Mirroring popular linux package manager repositories

### ISSUE THREAD

**Issue by andrew** [ipfs/package-managers#75]
I've started collecting a list of the most widespread linux distros and their package repositories, including size, update frequency, methods of mirroring, and lists of mirrors, with the aim of looking for repeating patterns that we can focus on supporting

Spoiler: All the linux package managers use regular rsync runs for mirroring, sometimes via a custom script that checks a last modified file time before attempting to download updates.

| Distro   | Size  | Frequency |
|----------|-------|-----------|
| Debian   | 2.4TB | 6 Hours   |
| Ubuntu   | 1.1TB | 6 Hours   |
| Fedora   | 1.5TB | 10 mins   |
| CentOS   | 400GB | 6 Hours   |
| FreeBSD  | 1.4TB | 24 Hours  |
| openSUSE | 3TB   | 6 Hours   |
| Arch     | 130GB | 1 Hour    |
| Gentoo   | 550GB | 4 Hours   |
| Alpine   | 560GB | 1 Hour    |

<hr />

## Debian 

Mirrors: https://www.debian.org/mirror/list

Mirroring method: [ftpsync](https://salsa.debian.org/mirror-team/archvsync/blob/master/bin/ftpsync) (rsync under the hood)

Mirroring docs: https://www.debian.org/mirror/ftpmirror

Total size: [2.4TB](https://www.debian.org/mirror/size)

Update frequency: 6 hours

## Ubuntu

Mirrors: https://launchpad.net/ubuntu/+archivemirrors

Mirroring method: https://wiki.ubuntu.com/Mirrors/Scripts (rsync)

Mirroring docs: https://wiki.ubuntu.com/Mirrors

Total size: 1.1TB

Update frequency: 6 hours

## Fedora

Mirrors: https://admin.fedoraproject.org/mirrormanager/

Mirroring method: [quick-fedora-mirror](https://pagure.io/quick-fedora-mirror) (rsync)

Mirroring docs: https://fedoraproject.org/wiki/Infrastructure/Mirroring

Total size: 1.5TB

Update frequency: 10 minutes 

## CentOS

Mirrors: https://www.centos.org/download/mirrors/

Mirroring method: rsync 

Mirroring docs: https://wiki.centos.org/HowTos/CreatePublicMirrors

Total size: 400GB

Update frequency: 6 hours

## FreeBSD

Mirrors: https://www.freebsd.org/doc/handbook/eresources-web.html

Mirroring method: rsync

Mirroring docs: https://www.freebsd.org/doc/en_US.ISO8859-1/articles/hubs/mirror-howto.html

Total size: 1.4 TB

Update frequency: daily

## openSUSE

Mirrors: https://mirrors.opensuse.org/

Mirroring method: rsync

Mirroring docs: https://en.opensuse.org/openSUSE:Mirror_howto

Total size: 3TB

Update frequency: 6 hours

## Arch Linux

Mirrors: https://www.archlinux.org/mirrorlist/all/

Mirroring method: rsync

Mirroring docs: https://wiki.archlinux.org/index.php/Mirrors

Total size: 130GB

Update frequency: 1 hour

## Gentoo

Mirrors: https://www.gentoo.org/support/rsync-mirrors/

Mirroring method: rsync

Mirroring docs: https://wiki.gentoo.org/wiki/Project:Infrastructure/Mirrors/Source

Total size: 550GB

Update frequency: 4 hours

## Alpine

Mirrors: https://mirrors.alpinelinux.org/

Mirroring method: rsync

Mirroring docs: https://wiki.alpinelinux.org/wiki/How_to_setup_a_Alpine_Linux_mirror

Total size: 560GB

Update frequency: 1 hour

**Comment by meiqimichelle** [comment]
This will get merged into #78. FYI n stuff.
