### ISSUE TITLE
Determine providing strategies for filesystem based package managers

### ISSUE THREAD

**Issue by michaelavila** [ipfs/package-managers#76]
Since we can't provide all of the blocks, which should we provide?

**Comment by andrew** [comment]
@michaelavila where's the current best place to go to read up on existing providing strategies and related docs in ipfs?

**Comment by andrew** [comment]
This thread on content routing and providing seems relevant: https://github.com/ipfs/notes/issues/162, linked from https://github.com/ipfs/notes/issues/212

**Comment by michaelavila** [comment]
@andrew yes.

FWIW: There are really two provider systems generally being discussed, (1) the providing system in libp2p and (2) the providing system in ipfs. I've been focused on the ipfs specific providing system, which up to this point has really just been bitswap aggressively providing every block it comes into contact with. Some of what's in these links is libp2p specific and some is useful for ipfs.

**Comment by andrew** [comment]
@michaelavila do you know of any existing benchmarks or performance tests that have been set up around providing? Like do we know what the current max size of a directory we can provide on the DHT today?

**Comment by michaelavila** [comment]
@andrew no, not that I know of.

**Comment by meiqimichelle** [comment]
@michaelavila is presenting on Friday (recorded call) for the latest on this and related work.

**Comment by momack2** [comment]
@michaelavila are there other pieces of documentation on our latest understanding of workable and non-workable solutions to improve providing in go-ipfs that should be indexed here?

**Comment by michaelavila** [comment]
@momack2 my apologies, I didn't see your message. I'm compiling this information into an issue that's not online yet. I'll circle back once it's online. To be honest, I don't have a lot of strategy specific information regarding package managers as we didn't spend too much time talking about it. I opened this ticket to start that, but my priorities were shifted a little.

**Comment by meiqimichelle** [comment]
And this is done! https://github.com/ipfs/package-managers/issues/84 . Also, there's a recording. We should find it and drop it here.

**Comment by momack2** [comment]
Recording: https://youtu.be/eSTEc4QFpc4
